version: '3.8'

services:
  app:
    image: yiiman/api-cli
    build: .
    ports:
      #- "127.0.0.1:80:80"      # Nginx
      - "127.0.0.1:3400:3000"  # Node.js app
    environment:
      - NODE_ENV=production
      - PORT
      - HOST
      - CLI_COMMAND
      - CLI_WORKING_DIR
      - API_KEY
    volumes:
      - ./logs:/usr/src/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s