version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"      # Nginx
      - "3000:3000"  # Node.js app
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - CLI_COMMAND=docker compose up -d
      # CLI Command Configuration
      - CLI_WORKING_DIR=~
    volumes:
      - ./logs:/usr/src/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s